12:46:19 PM:DEBUG [logger_base.py:14] Mensaje a nivel debug
12:46:19 PM:INFO [logger_base.py:15] Mensaje a nivel info
12:46:19 PM:WARNING [logger_base.py:16] Mensaje a nivel warning
12:46:19 PM:ERROR [logger_base.py:17] Mensaje a nivel error
12:46:19 PM:CRITICAL [logger_base.py:18] Mensaje a nivel critical
10:59:07 AM:DEBUG [Persona.py:52] 
            Id Persona: 1, 
            Nombre: Juan, 
            Apellido: Perez, 
            Email: jperez@mail.com

11:02:20 AM:DEBUG [Persona.py:52] 
            Id Persona: 1, 
            Nombre: Juan, 
            Apellido: Perez, 
            Email: jperez@mail.com

11:02:20 AM:DEBUG [Persona.py:54] 
            Id Persona: Jose, 
            Nombre: Lepez, 
            Apellido: ljose@mail.com, 
            Email: None

11:02:23 AM:DEBUG [Persona.py:52] 
            Id Persona: 1, 
            Nombre: Juan, 
            Apellido: Perez, 
            Email: jperez@mail.com

11:02:23 AM:DEBUG [Persona.py:54] 
            Id Persona: Jose, 
            Nombre: Lepez, 
            Apellido: ljose@mail.com, 
            Email: None

11:03:12 AM:DEBUG [Persona.py:52] 
            Id Persona: 1, 
            Nombre: Juan, 
            Apellido: Perez, 
            Email: jperez@mail.com

11:03:12 AM:DEBUG [Persona.py:54] 
            Id Persona: None, 
            Nombre: Jose, 
            Apellido: Lepez, 
            Email: ljose@mail.com

11:04:28 AM:DEBUG [Persona.py:52] 
            Id Persona: 1, 
            Nombre: Juan, 
            Apellido: Perez, 
            Email: jperez@mail.com

11:04:28 AM:DEBUG [Persona.py:54] 
            Id Persona: None, 
            Nombre: Jose, 
            Apellido: Lepez, 
            Email: ljose@mail.com

11:04:28 AM:DEBUG [Persona.py:56] 
            Id Persona: 1, 
            Nombre: None, 
            Apellido: None, 
            Email: None

11:24:47 AM:DEBUG [conexion.py:24] Conexion Exitosa: <connection object at 0x0000028DBC4028A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:33:21 AM:ERROR [conexion.py:27] Ocurrio un error de tipo: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgre"

11:34:07 AM:DEBUG [conexion.py:24] Conexion Exitosa: <connection object at 0x00000296CC2F28A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:34:07 AM:ERROR [conexion.py:41] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
11:36:01 AM:DEBUG [conexion.py:24] Conexion Exitosa: <connection object at 0x0000027F017028A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:36:01 AM:DEBUG [conexion.py:38] Se abrio correctamente el cursor: <cursor object at 0x0000027F03594040; closed: 0>
